package jsongen

import (
	"bytes"
	"go/format"
	"io"
	"text/template"

	"github.com/cockroachdb/errors"
	"github.com/effective-security/xlog"
	"google.golang.org/protobuf/compiler/protogen"
)

var logger = xlog.NewPackageLogger("github.com/effective-security/protoc-gen-go", "go-json")

// Options are the options to set for rendering the template.
type Options struct {
	Partial            bool
	Multiline          bool
	EnumsAsInts        bool
	EmitDefaults       bool
	OrigName           bool
	AllowUnknownFields bool
}

// This function is called with a param which contains the entire definition of a method.
func ApplyTemplate(w io.Writer, f *protogen.File, opts Options, withJsonOptions bool) error {
	buf := &bytes.Buffer{}
	if err := headerTemplate.Execute(buf, tplHeader{
		File: f,
	}); err != nil {
		return errors.Wrapf(err, "failed to execute template: %s", f.GeneratedFilenamePrefix)
	}

	if withJsonOptions {
		if err := jsonOptionsTemplate.Execute(buf, opts); err != nil {
			return errors.Wrapf(err, "failed to execute template: %s", f.GeneratedFilenamePrefix)
		}
	}

	if err := applyMessages(buf, f.Messages, opts); err != nil {
		return err
	}

	code, err := format.Source(buf.Bytes())
	if err != nil {
		return errors.Wrapf(err, "failed to format source: %s", f.GeneratedFilenamePrefix)
	}
	_, err = w.Write(code)
	return err
}

func applyMessages(w io.Writer, msgs []*protogen.Message, opts Options) error {
	for _, m := range msgs {

		if m.Desc.IsMapEntry() {
			logger.Infof("Skipping %s, mapentry message", m.GoIdent.GoName)
			continue
		}

		logger.Infof("Processing %s", m.GoIdent.GoName)
		if err := messageTemplate.Execute(w, tplMessage{
			Message: m,
			Options: opts,
		}); err != nil {
			return errors.Wrapf(err, "failed to execute template: %s", m.GoIdent.GoName)
		}

		if err := applyMessages(w, m.Messages, opts); err != nil {
			return err
		}

	}

	return nil
}

type tplHeader struct {
	*protogen.File
}

type tplMessage struct {
	*protogen.Message
	Options
}

var (
	headerTemplate = template.Must(template.New("header").Parse(`
// Code generated by protoc-gen-go-json. DO NOT EDIT.
// source: {{.Proto.Name}}

package {{.GoPackageName}}

import (
	"google.golang.org/protobuf/encoding/protojson"
)
`))

	jsonOptionsTemplate = template.Must(template.New("message").Parse(`
var JsonMarshalOptions = protojson.MarshalOptions {
	UseEnumNumbers: {{.EnumsAsInts}},
	EmitUnpopulated: {{.EmitDefaults}},
	UseProtoNames: {{.OrigName}},
	AllowPartial: {{.Partial}},
	{{- if .Multiline}}
	Multiline: true,
	Indent: "\t",
	{{- end}}
}

var JsonUnmarshalOptions = protojson.UnmarshalOptions {
	AllowPartial: {{.Partial}},
	DiscardUnknown: {{.AllowUnknownFields}},
}

// MarshalJSON implements json.Marshaler
func MarshalJSON(v any) ([]byte, error) {
	if JsonMarshalOptions.Multiline {
		return json.MarshalIndent(v, "", JsonMarshalOptions.Indent)
	}
	return json.Marshal(v)
}
`))

	messageTemplate = template.Must(template.New("message").Parse(`
// MarshalJSON implements json.Marshaler
func (msg *{{.GoIdent.GoName}}) MarshalJSON() ([]byte,error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *{{.GoIdent.GoName}}) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}
`))
)
