// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.27.2
// source: resources.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service is the service name providing a resource.
	Service string `protobuf:"bytes,1,opt,name=Service,proto3" json:"Service,omitempty"`
	// Name is the plural name of the resource.
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// SingularName is the singular name of the resource.  This allows clients
	// to handle plural and singular opaquely. The SingularName is more correct
	// for reporting status on a single item and both singular and plural are
	// allowed from the CLI interface.
	SingularName string `protobuf:"bytes,3,opt,name=SingularName,proto3" json:"SingularName,omitempty"`
	// Kind is the type of resource.
	Kind string `protobuf:"bytes,4,opt,name=Kind,proto3" json:"Kind,omitempty"`
	// Scope is the scope of the resource.
	Scope string `protobuf:"bytes,5,opt,name=Scope,proto3" json:"Scope,omitempty"`
	// Verbs is the list of verbs that can be performed on the resource:
	// Get, List, Create, Update, Delete
	Verbs         []string `protobuf:"bytes,6,rep,name=Verbs,proto3" json:"Verbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResource) Reset() {
	*x = APIResource{}
	mi := &file_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResource) ProtoMessage() {}

func (x *APIResource) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResource.ProtoReflect.Descriptor instead.
func (*APIResource) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{0}
}

func (x *APIResource) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *APIResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIResource) GetSingularName() string {
	if x != nil {
		return x.SingularName
	}
	return ""
}

func (x *APIResource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *APIResource) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *APIResource) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

type TableColumnDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the identifier for the column, corresponds to the resource field
	// name
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// Name is a human readable name for the column.
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// Type is an OpenAPI type definition for this column, such as number,
	// integer, string, or array. See
	// https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types
	// for more.
	Type string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	// Format is an optional OpenAPI type modifier for this column. A format
	// modifies the type and imposes additional rules, like date or time
	// formatting for a string. The 'name' format is applied to the primary
	// identifier column which has type 'string' to assist in clients
	// identifying column is the resource name. See
	// https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types
	// for more.
	Format string `protobuf:"bytes,4,opt,name=Format,proto3" json:"Format,omitempty"`
	// Description is a human readable description of this column.
	Description string `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	// SearchOptions is populated from es.api.search option.
	SearchOptions SearchOption_Enum `protobuf:"varint,6,opt,name=SearchOptions,proto3,enum=es.api.SearchOption_Enum" json:"SearchOptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableColumnDefinition) Reset() {
	*x = TableColumnDefinition{}
	mi := &file_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableColumnDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableColumnDefinition) ProtoMessage() {}

func (x *TableColumnDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableColumnDefinition.ProtoReflect.Descriptor instead.
func (*TableColumnDefinition) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{1}
}

func (x *TableColumnDefinition) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *TableColumnDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableColumnDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TableColumnDefinition) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *TableColumnDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TableColumnDefinition) GetSearchOptions() SearchOption_Enum {
	if x != nil {
		return x.SearchOptions
	}
	return SearchOption_None
}

// TableRow is an individual row in a table.
type TableRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cells will be as wide as the column definitions array and contain string
	// representation of basic types as:
	// strings, numbers (float64 or int64), booleans, simple maps, lists, or
	// null.
	// See the type field of the column definition for a more detailed
	// description.
	Cells         []string `protobuf:"bytes,1,rep,name=Cells,proto3" json:"Cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableRow) Reset() {
	*x = TableRow{}
	mi := &file_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRow) ProtoMessage() {}

func (x *TableRow) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRow.ProtoReflect.Descriptor instead.
func (*TableRow) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{2}
}

func (x *TableRow) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

// ListMeta describes metadata that synthetic resources must have, including
// lists and various status objects. A resource may have only one of
// {ObjectMeta, ListMeta}.
type ListMeta struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	NextCursor string                 `protobuf:"bytes,1,opt,name=NextCursor,proto3" json:"NextCursor,omitempty"`
	HasMore    bool                   `protobuf:"varint,2,opt,name=HasMore,proto3" json:"HasMore,omitempty"`
	// TotalCount is the total number of items in the list,
	// available for the responses from Search when facets exist.
	// TotalCount may not be present in all responses, like from RDS.
	TotalCount    int64 `protobuf:"varint,3,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeta) Reset() {
	*x = ListMeta{}
	mi := &file_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeta) ProtoMessage() {}

func (x *ListMeta) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeta.ProtoReflect.Descriptor instead.
func (*ListMeta) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{3}
}

func (x *ListMeta) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListMeta) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListMeta) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ObjectMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the identifier for the resource, or empty if the resource is a list
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// Kind is the type of resource this table represents.
	Kind string `protobuf:"bytes,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	// URI is the URI of the resource.
	URI           string `protobuf:"bytes,3,opt,name=URI,proto3" json:"URI,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_resources_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectMeta) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ObjectMeta) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ObjectMeta) GetURI() string {
	if x != nil {
		return x.URI
	}
	return ""
}

// Table is a generic table structure for representing tabular data.
type Table struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ObjectMeta is the metadata of the resource.
	ObjectMeta *ObjectMeta `protobuf:"bytes,1,opt,name=ObjectMeta,proto3" json:"ObjectMeta,omitempty"`
	// ListMeta is the metadata of the list.
	ListMeta *ListMeta `protobuf:"bytes,2,opt,name=ListMeta,proto3" json:"ListMeta,omitempty"`
	// Columns is an array of column definitions.
	Columns []*TableColumnDefinition `protobuf:"bytes,3,rep,name=Columns,proto3" json:"Columns,omitempty"`
	// Rows is an array of rows.
	Rows          []*TableRow `protobuf:"bytes,4,rep,name=Rows,proto3" json:"Rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_resources_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{5}
}

func (x *Table) GetObjectMeta() *ObjectMeta {
	if x != nil {
		return x.ObjectMeta
	}
	return nil
}

func (x *Table) GetListMeta() *ListMeta {
	if x != nil {
		return x.ListMeta
	}
	return nil
}

func (x *Table) GetColumns() []*TableColumnDefinition {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Table) GetRows() []*TableRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_resources_proto protoreflect.FileDescriptor

const file_resources_proto_rawDesc = "" +
	"\n" +
	"\x0fresources.proto\x12\x06es.api\x1a\x11annotations.proto\"\x9f\x01\n" +
	"\vAPIResource\x12\x18\n" +
	"\aService\x18\x01 \x01(\tR\aService\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\"\n" +
	"\fSingularName\x18\x03 \x01(\tR\fSingularName\x12\x12\n" +
	"\x04Kind\x18\x04 \x01(\tR\x04Kind\x12\x14\n" +
	"\x05Scope\x18\x05 \x01(\tR\x05Scope\x12\x14\n" +
	"\x05Verbs\x18\x06 \x03(\tR\x05Verbs\"\xca\x01\n" +
	"\x15TableColumnDefinition\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\tR\x04Type\x12\x16\n" +
	"\x06Format\x18\x04 \x01(\tR\x06Format\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\x12?\n" +
	"\rSearchOptions\x18\x06 \x01(\x0e2\x19.es.api.SearchOption.EnumR\rSearchOptions\" \n" +
	"\bTableRow\x12\x14\n" +
	"\x05Cells\x18\x01 \x03(\tR\x05Cells\"d\n" +
	"\bListMeta\x12\x1e\n" +
	"\n" +
	"NextCursor\x18\x01 \x01(\tR\n" +
	"NextCursor\x12\x18\n" +
	"\aHasMore\x18\x02 \x01(\bR\aHasMore\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x03 \x01(\x03R\n" +
	"TotalCount\"B\n" +
	"\n" +
	"ObjectMeta\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Kind\x18\x02 \x01(\tR\x04Kind\x12\x10\n" +
	"\x03URI\x18\x03 \x01(\tR\x03URI\"\xc8\x01\n" +
	"\x05Table\x122\n" +
	"\n" +
	"ObjectMeta\x18\x01 \x01(\v2\x12.es.api.ObjectMetaR\n" +
	"ObjectMeta\x12,\n" +
	"\bListMeta\x18\x02 \x01(\v2\x10.es.api.ListMetaR\bListMeta\x127\n" +
	"\aColumns\x18\x03 \x03(\v2\x1d.es.api.TableColumnDefinitionR\aColumns\x12$\n" +
	"\x04Rows\x18\x04 \x03(\v2\x10.es.api.TableRowR\x04RowsB1Z/github.com/effective-security/protoc-gen-go/apib\x06proto3"

var (
	file_resources_proto_rawDescOnce sync.Once
	file_resources_proto_rawDescData []byte
)

func file_resources_proto_rawDescGZIP() []byte {
	file_resources_proto_rawDescOnce.Do(func() {
		file_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resources_proto_rawDesc), len(file_resources_proto_rawDesc)))
	})
	return file_resources_proto_rawDescData
}

var file_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_resources_proto_goTypes = []any{
	(*APIResource)(nil),           // 0: es.api.APIResource
	(*TableColumnDefinition)(nil), // 1: es.api.TableColumnDefinition
	(*TableRow)(nil),              // 2: es.api.TableRow
	(*ListMeta)(nil),              // 3: es.api.ListMeta
	(*ObjectMeta)(nil),            // 4: es.api.ObjectMeta
	(*Table)(nil),                 // 5: es.api.Table
	(SearchOption_Enum)(0),        // 6: es.api.SearchOption.Enum
}
var file_resources_proto_depIdxs = []int32{
	6, // 0: es.api.TableColumnDefinition.SearchOptions:type_name -> es.api.SearchOption.Enum
	4, // 1: es.api.Table.ObjectMeta:type_name -> es.api.ObjectMeta
	3, // 2: es.api.Table.ListMeta:type_name -> es.api.ListMeta
	1, // 3: es.api.Table.Columns:type_name -> es.api.TableColumnDefinition
	2, // 4: es.api.Table.Rows:type_name -> es.api.TableRow
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_resources_proto_init() }
func file_resources_proto_init() {
	if File_resources_proto != nil {
		return
	}
	file_annotations_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resources_proto_rawDesc), len(file_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resources_proto_goTypes,
		DependencyIndexes: file_resources_proto_depIdxs,
		MessageInfos:      file_resources_proto_msgTypes,
	}.Build()
	File_resources_proto = out.File
	file_resources_proto_goTypes = nil
	file_resources_proto_depIdxs = nil
}
